"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
"""
sum = 0
fib_l = [1,2]
flag = True
i = 2
while flag:
	ith_term = fib_nums[i-2] + fib_nums[i-1]
	if ith_term > 4000000:
		flag = False
	else:
		fib_nums.append(ith_term)
	i += 1
print(str(fib_nums))

for t in fib_nums:
	if t % 2 == 0:
		sum += t
print sum


